name: wallet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # QR code generation
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets (istersen uncomment aÃ§abilirsin)
  # assets:
  #   - assets/images/

  # Fonts (ilgili dosyalar varsa ekleyebilirsin)
  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: assets/fonts/YourFont-Regular.ttf
